name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 1" # Mondays at 11 AM UTC (8 AM BRT)

jobs:
  health-check:
    name: Health check
    runs-on: ubuntu-latest
    steps:
      - name: Update and install sudo for Act
        if: ${{ env.ACT }} # runs this step only when testing locally with 'act'
        run: |
          apt update
          apt upgrade
          apt install sudo

      - name: Update
        if: ${{ !env.ACT }} # skips this step when testing locally with 'act'
        run: |
          sudo apt-get update
          sudo apt-get upgrade

      - name: Install curl
        run: |
          sudo apt-get -y install curl
          curl --version

      - name: Check the deployed service URL
        id: health-check-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.HEALTH_CHECK_URL}}
          method: ${{secrets.HEALTH_CHECK_METHOD}}
          retry: 12
          retryWait: 5000

      - name: Show Response
        run: |
          echo ${{ steps.health-check-request.outputs.response }}
