name: SonarCloud Coverage
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Yarn if necessary
        if: ${{ !env.ACT }} # skips this step when testing locally with 'act'
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn

      - name: Test and coverage
        run: yarn coverage

      - name: SonarCloud Scan
        if: ${{ !env.ACT }} # skips this step when testing locally with 'act'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
